version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: poetry-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - poetry-network

  poetry-api:
    build: .
    container_name: poetry-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/poetry_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - poetry-network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:

networks:
  poetry-network:
    driver: bridge
